# Generated by Django 5.2.5 on 2025-08-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="room_images/",
                verbose_name="Изображение",
            ),
        ),
    ]
