# Generated by Django 5.2.5 on 2025-08-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_room_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="organization",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="organization",
            name="phone",
            field=models.CharField(blank=True, max_length=30, verbose_name="Телефон"),
        ),
    ]
