# Generated by Django 5.2.5 on 2025-08-20 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_organization_description_organization_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (1, "Понедельник"),
                            (2, "Вторник"),
                            (3, "Среда"),
                            (4, "Четверг"),
                            (5, "Пятница"),
                            (6, "Суббота"),
                            (7, "Воскресенье"),
                        ],
                        verbose_name="День недели",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                ("end_time", models.TimeField(verbose_name="Время окончания")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена за час"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_rules",
                        to="booking.room",
                        verbose_name="Зал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Правило расписания",
                "verbose_name_plural": "Правила расписания",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.DeleteModel(
            name="RoomSchedule",
        ),
    ]
