# Generated by Django 5.2.5 on 2025-08-25 16:49

from django.db import migrations
import datetime

def populate_initial_data(apps, schema_editor):
    """
    Заполняет базу данных начальными данными для организации, залов и правил расписания.
    """
    Organization = apps.get_model('booking', 'Organization')
    Room = apps.get_model('booking', 'Room')
    ScheduleRule = apps.get_model('booking', 'ScheduleRule')

    # 1. Создаем организацию
    big_z_org, created = Organization.objects.get_or_create(
        name="Продюсерский центр Big Z",
        defaults={
            "description": "Творческое пространство в самом сердце города.",
            "phone": "+7 (999) 123-45-67",
            "email": "info@bigz.ru"
        }
    )

    # Если организация уже была, ничего не делаем, чтобы избежать дублирования
    if not created:
        return

    # 2. Создаем несколько залов
    room1 = Room.objects.create(
        organization=big_z_org,
        title="Репетиционный зал 'Восток'",
        description="Просторный зал с барабанной установкой и полным бэклайном."
    )
    room2 = Room.objects.create(
        organization=big_z_org,
        title="Студия звукозаписи 'Z-Rec'",
        description="Профессиональная студия для записи вокала и инструментов."
    )
    room3 = Room.objects.create(
        organization=big_z_org,
        title="Фотостудия 'Циклорама'",
        description="Зал с белой циклорамой для фото- и видеосъемок."
    )
    rooms = [room1, room2, room3]

    # 3. Создаем правила расписания для каждого зала
    for room in rooms:
        # Будни
        for day in range(1, 6): # Понедельник-Пятница
            ScheduleRule.objects.create(
                room=room,
                day_of_week=day,
                start_time=datetime.time(10, 0),
                end_time=datetime.time(22, 0),
                price=1000
            )
        # Выходные
        for day in range(6, 8): # Суббота-Воскресенье
            ScheduleRule.objects.create(
                room=room,
                day_of_week=day,
                start_time=datetime.time(12, 0),
                end_time=datetime.time(20, 0),
                price=1500
            )

class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_schedulerule_delete_roomschedule"),
    ]

    operations = [
        migrations.RunPython(populate_initial_data),
    ]
