# Generated by Django 5.2.5 on 2025-08-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_populate_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="slot_duration_minutes",
            field=models.IntegerField(
                default=60, verbose_name="Длительность слота (минут)"
            ),
        ),
    ]
